### ISSUE TITLE
error : [8UC3] is not a color format. but [bgr8] is. The conversion does not make sense. how to fix it?

### ISSUE THREAD

**Issue by GaengSu** [thomasgallo/mono_slam_tensorflow#8]
Hello.
Thanks to your document, I got a lot of help :)
I followed your repository in order. However, an error occurs during the object-detection.. (_**rosrun image_view image_view image:=/object_detection**_)
In terminal,
[ INFO] [1581604382.163507053]: Using transport "raw"
[ERROR] [1581604382.445158498]: Unable to convert '8UC3' image for display: 'cv_bridge.cvtColorForDisplay() while trying to convert image from '8UC3' to 'bgr8' an exception was thrown ([8UC3] is not a color format. but [bgr8] is. The conversion does not make sense)'
that statement is printed.
And detections_image window dosn't work.
How can i fix it?
![error_pic2](https://user-images.githubusercontent.com/53466091/74445380-a2795b80-4eb9-11ea-961f-d2c6766a7ef0.jpg)

**Comment by tdepalle** [comment]
Hi ! 
I am supposing you launched cob_people_object_detection_tensorflow.launch.
For me changing the line 145 in src/cob_people_object_detection_tensorflow.py by
` msg_im = self._bridge.cv2_to_imgmsg( image_processed, "bgr8")` worked. 

Let me know if it worked for you too.

**Comment by GaengSu** [comment]
It works perfectly!! Thank you for your reply :)
